fragment DocumentPageFragment on Page {
  id
  handle
  title
  body
}

query {
  shop {
    paymentSettings {
      enabledPresentmentCurrencies
    }
    description
    moneyFormat
    name
    primaryDomain {
      host
      sslEnabled
      url
    }
  }
  privacyPolicyPage: pageByHandle(handle: "privacy-policy") {
    ...DocumentPageFragment
  }
  termsOfServicePage: pageByHandle(handle: "terms-of-service") {
    ...DocumentPageFragment
  }
  faqPage: pageByHandle(handle: "faq") {
    ...DocumentPageFragment
  }
}
